repositories:
- name: stable
  url: https://charts.helm.sh/stable

helmDefaults:
  tillerless: true
  verify: false
  wait: true
  timeout: 600
  force: true

releases:
- name: metrics-server
  chart: stable/metrics-server
  namespace: kube-system
  version: 2.11.4
  values:
  - "./charts/metrics-server/values.yaml"

- name: cluster-autoscaler
  chart: stable/cluster-autoscaler
  version: 8.0.0
  namespace: kube-system
  values:
  - "./charts/cluster-autoscaler/values.yaml"

- name: ingress
  chart: stable/nginx-ingress
  version: 1.41.3
  namespace: kube-system
  values:
  - "./charts/nginx-ingress/values.yaml"

- name: prom
  chart: stable/prometheus-operator
  version: 9.3.2
  namespace: monitoring
  values:
  - "./charts/prometheus/values.yaml"
  set:
  - name: grafana.adminPassword
    value: HelloWorld

- name: jenkins
  chart: stable/jenkins
  version: 2.5.4
  namespace: cicd
  values:
  - "./charts/jenkins/values.yaml"
  set:
  - name: master.adminPassword
    value: HelloWorld
