persistence:
  enabled: true
  size: "3Gi"

master:
  tag: "lts"
  ingress:
    enabled: true
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.antoniorufo.com
    jenkinsUrl: jenkins.antoniorufo.com
  adminPassword: HelloWorld
  overwritePlugins: true
  installPlugins:
    - kubernetes:1.25.7
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.23
    - git:4.2.2
    - configuration-as-code:1.41
    - github-oauth:0.33
    - github-branch-source:2.9.2
    - blueocean:1.23.2
  JCasC:
    enabled: true
    configScripts:
      main-config: |
        jenkins:
          securityRealm:
            github:
              githubWebUri: "https://github.com"
              githubApiUri: "https://api.github.com"
              clientID: "f862e53757865957dbc6"
              clientSecret: "6a442d27a78ce26c43c1e735bca0399c51e7d646"
              oauthScopes: "read:org,user:email"
        credentials:
          system:
            domainCredentials:
              - credentials:
                - gitHubApp:
                    appID: "93106"
                    description: "EKS GitHub app"
                    id: "eks-github-app"
                    privateKey: |
                      -----BEGIN PRIVATE KEY-----
                      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDDrT/u+6FIMd4t
                      ieu4AaK6R4JFOEyksIiK/1i1COogHUhvZehPc+aQhq0SWZoPlcKRRit651BqJ4cl
                      U2Nlx6HJqkNjveZP5RjE79mYmnbjIywrrHTScjBbIWqVRN+VHWmFqvpYOvQbbkve
                      googXDpfRIDTzJvtrAgDVXUssrQumUvZv7COiuYPkA6SS6xfcJg60PTe3kHG4MH6
                      HXCkKawTW0JUP11wIKB3lMV+DbIFdhsL5LM02t0gWw85D2ZVYfTXrJz7SfkJ476s
                      hcY0C5T/By08AkkOK1ym00EG2ekSLe4QpajJvYJMvVNp55un/nkXzh/GnMo5JDFA
                      9D9Fz1UvAgMBAAECggEBAIjMQSsZPcrUGiiqCGIuuo4SWg98aZClXgAWvfRqVAu5
                      jR9cFkodk+4sSSjP/XWx1EFt1g3pUv2zvraoko/gPcpXvx8m7rGiT2u25t/Z9Q2c
                      VFAAE/fgHtBHD1Vlvg1ob5IkUzqFlIzs0huwFVLER4a8xHfNzqEdKMjz4KQsFu2P
                      wwwTPXK73UWKg5B1vEgWQNUa8VvPnO773kDRU6gbvkAYBbXWOK31UNfN/3sLMita
                      +X3SEra7b5lekvvlaQJMDkZoC8d8hlFugr2M8TZeluKsJOSJIS1fN9KVwbNjL2iA
                      zew9okQeJdsRzxkQwFxS9lQd17yUpvC7URdxqmLrseECgYEA6bGfYqTtqo41p2XO
                      exjYG2MzeE7oBH7ssFe12mzWziRFdDetlLQ4flT5Ysmsh68TKxSghGWITuaEJKg4
                      IzYsL4soa3pos0U/1Zd6I04toOduW/+CErWnYkPxbZeDmXDMhhIcfb/HSVVcZfOD
                      ZaxSdhlfX5pRewnL8wcjZPj6wr8CgYEA1lqrKoy86FsymmID3M+z95ivXpCSMScp
                      ap8u2tPXs2uCruU0L5kO0mmvjf2FYcucO10weoEKodJ7YufS8v/kXS94llNvgfTS
                      X+1FK+w1uamsyg7pqQDAVpGseyFPIeBk/x+N9CeiaTZzmwDu2YtBnKXwDPKfvQEI
                      1dTS+Ki1uZECgYEAgGqPyBgTVc6xoxwpm7EqR9p6VRkfHCFXFQwNrUpzu3FpDRTv
                      eLCT/q/ZHrTt7t2A7gJ2tmpIvfqkELSzrH2/SBzzCCSK1kAudMO5ZR83qZyjI0DD
                      jF5v7Wqih3Nj6HR4nw/iwiMZcq3KiWeIA93urmEA7LsTHUZj4VdB1uGOgmcCgYBX
                      yjCaL6Pa4ib6dbQxRlvlxwHkD//f47MhuOo+s05/bEPMj5DtAZnBcYl19OQg5nwp
                      EASf16PcHNFt85ZA8a68v4l6v9dGeVeD9DBFSevDC4v6AVuPXQBpNCZZE45OSJH0
                      rx67ZVQuFSAJ1rr8G/2WQ5vqIaBsjzToJs71ClvLEQKBgDaZEJ0EEQiULzL5pGdk
                      NUe2NK4DfGDTDcBxZbe8qwo9KH1me1Fs4wpjtOEaqvdk9cI7VBjzbcmjm/yoXn+H
                      hTwCZ25lk58UTY4zFi+uqK8onksMQwo5E4zzIIltPU7TbnICq0bxSrLqs79ws6JT
                      Pyp9MhuJR9aSsnsgG8dECbhw
                      -----END PRIVATE KEY-----
      main-config: |
        jenkins:
          clouds:
            - kubernetes:
                name: "main-k8s-cluster"
                serverUrl: "https://kubernetes.default"
                skipTlsVerify: true
                namespace: "cicd"
                jenkinsUrl: "https://jenkins:8080/"
                jenkinsTunnel: "jenkins-agent:50000"
