###############################################################################
# EKS Output
###############################################################################
output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

###############################################################################
# kubectl config
###############################################################################
output "summary" {
  value = <<EOF

## Run to configure Kubectl to connect to your new EKS cluster:
$ aws eks update-kubeconfig --name ${module.eks.cluster_id}


EOF

  description = "Configures kubectl so that you can connect to an Amazon EKS cluster. `terraform output summary` "
}
